UPD(Docs) Polishing README.md
rh-messaging-qe/iqa_testsuite pull request #24
Opened 2019-03-13 10:25 UTC by michalxo

2019-03-13 13:45 UTC, enkeys commented
I provided an update with fixes too. 
@michalxo are you ok with it too?

2019-03-13 15:15 UTC, fgiorgetti requested changes
QPID Broker is not implemented yet, so maybe we can remove it from the supported list of brokers for now.

We must also include "pytest_iqa" as a dependency (in "Dependencies and projects" section).

Rest of the changes, look good to me.

2019-03-13 15:41 UTC, fgiorgetti approved these changes
Looks good to me. Thanks!

2019-03-14 08:38 UTC, lenosi approved these changes

2019-03-14 08:43 UTC, merged